#!/bin/bash
source /macqiime/configs/bash_profile.txt
/macqiime/bin/python /macqiime/bin/alpha_rarefaction.py -i /Users/KenBradshaw/git/pipeline/data_and_script_dir/otus/otu_table_no_singletons.biom -m /Users/KenBradshaw/git/pipeline/data_and_script_dir/mapping_files/SFBR_RE_16S_mapping_file.txt -o /Users/KenBradshaw/git/pipeline/data_and_script_dir/otus/alpha_rare/ -f  -t /Users/KenBradshaw/git/pipeline/data_and_script_dir/otus/rep_set.tre
