#Remove Chimera reads using usearch from (http://www.drive5.com/usearch/)
```{r,echo=FALSE,eval=TRUE,include=FALSE,messages=TRUE,error=TRUE}
#Files with dimension
list.files(SFBR_notag.write.dir)
list.files(modified.write.dir)
  #sample ids from 04pipeline_remove_headspace.R
  sample.id.3 
rmchimerafiles <- paste("rm_chimera_",sample.id.3,".fasta",sep = "")
rmchimerawithpath <- paste(rmchimera.dir,rmchimerafiles,sep = "")

#Delete any existing files in the modified headspace directory and removed chimeras directory
modified.notag.rm <- paste(modified.write.dir,list.files(modified.write.dir),sep="")
unlink(modified.notag.rm,recursive=FALSE,force=FALSE)
rmchimera.dir.rm <- paste(rmchimera.dir,list.files(rmchimera.dir),sep="")
unlink(rmchimera.dir.rm,recursive=FALSE,force=FALSE)


#copy Modified Headspace files from the SFBR_notag directory to the SFBR_modified_headspace directory
modified_files <- paste("NoTag_trimmed_",sample.id.3,"_Modified.fasta",sep = "")
modified_files_copied <- paste(SFBR_notag.write.dir,"/",modified_files, sep = "")
file.copy(modified_files_copied,modified.write.dir)
```
##Remove chimeras file command
```{r,echo=TRUE,eval=TRUE,include=TRUE,messages=TRUE,error=TRUE}
#file command
remove_chimera.command <- paste(usearch.dir,"usearch8.0.1517_i86osx32"," --uchime_ref ", modified_files_copied, " -db ", usearch.dir, "gold.fa", " --nonchimeras ",rmchimerawithpath," -strand plus", sep = "")

for(command in remove_chimera.command){
  system(command)
}
```
###Files with chimera reads removed
```{r,echo=TRUE,eval=TRUE,include=TRUE,messages=TRUE,error=TRUE}
rmchimerawithpath
```
